const programs = [
  {
    id: 1,
    nombre: 'Hogar permanente diamante',
    descripcion: 'Nuestro programa diamante ofrece un entorno exclusivo, con atención personalizada y de alta calidad para residentes que buscan una vida tranquila y cómoda.',
    incluye: [
      'Habitación privada con baño independiente.',
      'Aire acondicionado.',
      'Tres comidas principales y 2 meriendas.',
      'Aseo y mantenimiento a la habitación diario.',
      'Cuidado de pertenencias.',
      'Lavado y planchado de ropa.',
      'Salidas con acompañamiento (previamente autorizadas por su responsable directo).',
      'Asistencia en comunicación virtual con familiares.',
      'Acompañamiento de auxiliares de enfermería las 24 h.',
      'AMI, servicio de asistencia primaria y emergencias.',
      'Actividades recreativas todas las semanas.',
      'Visitas semanales de especialistas de la salud integral como psicólogos, fisioterapeutas, etc.',
      'Terapeuta ocupacional.',
      'Dinámicas de integración familiar los fines de semana.',
      'Suministro de medicamentos autorizados por sus médicos tratantes.',
      'Toma de signos vitales.',
      'Apoyo en las actividades de la vida diaria.',
      'Vigilancia nocturna de comportamiento al dormir.',
      'Afiliación a un seguro funerario si no lo posee.'
    ],
    url: 'https://res.cloudinary.com/de5tm90td/image/upload/f_auto,q_auto,w_800/v1/assets/wkqvcs1q0kpr5xyxrmk1'
  },
  {
    id: 2,
    nombre: 'Hogar permanente esmeralda',
    descripcion: 'El programa esmeralda ofrece un hogar con todos los servicios esenciales y un ambiente cálido, ideal para aquellos que requieren atención continua.',
    incluye: [
      'Habitación privada.',
      'Aire acondicionado.',
      'Tres comidas principales y 2 meriendas.',
      'Aseo y mantenimiento a la habitación diario.',
      'Cuidado de pertenencias.',
      'Lavado y planchado de ropa.',
      'Salidas con acompañamiento (previamente autorizadas por su responsable directo).',
      'Asistencia en comunicación virtual con familiares.',
      'Acompañamiento de auxiliares de enfermería las 24 h.',
      'AMI, servicio de asistencia primaria y emergencias.',
      'Actividades recreativas todas las semanas.',
      'Visitas semanales de especialistas de la salud integral como psicólogos, fisioterapeutas, etc.',
      'Terapeuta ocupacional.',
      'Dinámicas de integración familiar los fines de semana.',
      'Suministro de medicamentos autorizados por sus médicos tratantes.',
      'Toma de signos vitales.',
      'Apoyo en las actividades de la vida diaria.',
      'Vigilancia nocturna de comportamiento al dormir.',
      'Afiliación a un seguro funerario si no lo posee.'
    ],
    url: 'https://res.cloudinary.com/de5tm90td/image/upload/f_auto,q_auto,w_800/v1/assets/zzmeb9cvifsudaapxvjr'
  },
  {
    id: 3,
    nombre: 'Hogar permanente oro',
    descripcion: 'Nuestro programa oro brinda atención integral y confort, enfocado en ofrecer lo mejor en calidad de vida para los residentes con necesidades más exigentes.',
    incluye: [
      'Habitación privada.',
      'Tres comidas principales y 2 meriendas.',
      'Aseo y mantenimiento a la habitación diario.',
      'Cuidado de pertenencias.',
      'Lavado y planchado de ropa.',
      'Salidas con acompañamiento (previamente autorizadas por su responsable directo).',
      'Asistencia en comunicación virtual con familiares.',
      'Acompañamiento de auxiliares de enfermería las 24 h.',
      'AMI, servicio de asistencia primaria y emergencias.',
      'Actividades recreativas todas las semanas.',
      'Visitas semanales de especialistas de la salud integral como psicólogos, fisioterapeutas, etc.',
      'Terapeuta ocupacional.',
      'Dinámicas de integración familiar los fines de semana.',
      'Suministro de medicamentos autorizados por sus médicos tratantes.',
      'Toma de signos vitales.',
      'Apoyo en las actividades de la vida diaria.',
      'Vigilancia nocturna de comportamiento al dormir.',
      'Afiliación a un seguro funerario si no lo posee.'
    ],
    url: 'https://res.cloudinary.com/de5tm90td/image/upload/f_auto,q_auto,w_800/v1/assets/mh5udorw9q18bwx8zoxi'
  },
  {
    id: 4,
    nombre: 'Hogar permanente VIP compartido',
    descripcion: 'Este programa VIP compartido permite a los residentes disfrutar de una experiencia de calidad, con la comodidad de compartir el espacio con otro residente.',
    incluye: [
      'Habitación compartida con baño compartido.',
      'Aire acondicionado.',
      'Tres comidas principales y 2 meriendas.',
      'Aseo y mantenimiento a la habitación diario.',
      'Cuidado de pertenencias.',
      'Lavado y planchado de ropa.',
      'Salidas con acompañamiento (previamente autorizadas por su responsable directo).',
      'Asistencia en comunicación virtual con familiares.',
      'Acompañamiento de auxiliares de enfermería las 24 h.',
      'AMI, servicio de asistencia primaria y emergencias.',
      'Actividades recreativas todas las semanas.',
      'Visitas semanales de especialistas de la salud integral como psicólogos, fisioterapeutas, etc.',
      'Terapeuta ocupacional.',
      'Dinámicas de integración familiar los fines de semana.',
      'Suministro de medicamentos autorizados por sus médicos tratantes.',
      'Toma de signos vitales.',
      'Apoyo en las actividades de la vida diaria.',
      'Vigilancia nocturna de comportamiento al dormir.',
      'Afiliación a un seguro funerario si no lo posee.'
    ],
    url: 'https://res.cloudinary.com/de5tm90td/image/upload/f_auto,q_auto,w_800/v1/assets/mh5udorw9q18bwx8zoxi'
  },
  {
    id: 5,
    nombre: 'Hogar vacaciones',
    descripcion: 'Este programa es ideal para quienes requieren estancias cortas, garantizando todos los servicios esenciales durante su visita.',
    incluye: [
      'Tres comidas principales y 2 meriendas.',
      'Aseo y mantenimiento a la habitación diario.',
      'Cuidado de pertenencias.',
      'Lavado y planchado de ropa.',
      'Salidas con acompañamiento (previamente autorizadas por su responsable directo).',
      'Asistencia en comunicación virtual con familiares.',
      'Acompañamiento de auxiliares de enfermería las 24 h.',
      'AMI, servicio de asistencia primaria y emergencias durante su estancia.',
      'Actividades recreativas.',
      'Vigilancia de toma de medicamentos autorizados por sus médicos tratantes.',
      'Toma de signos vitales.',
      'Apoyo en las actividades de la vida diaria.',
      'Vigilancia nocturna.'
    ],
    url: 'https://res.cloudinary.com/de5tm90td/image/upload/f_auto,q_auto,w_800/v1/assets/w7nkefh10dzvsa3kd5r8'
  },
  {
    id: 6,
    nombre: 'Hogar cuidado diario',
    descripcion: 'Este plan está diseñado para quienes necesitan cuidado en su rutina diaria, sin necesidad de residencia completa, con servicios adaptados a sus necesidades.',
    incluye: [
      'Tres comidas principales y 2 meriendas.',
      'Aseo y mantenimiento a la habitación diario.',
      'Cuidado de pertenencias.',
      'Salidas con acompañamiento (previamente autorizadas por su responsable directo).',
      'Asistencia en comunicación virtual con familiares.',
      'Acompañamiento de auxiliares de enfermería durante su estancia.',
      'AMI, servicio de asistencia primaria y emergencias durante su estancia.',
      'Actividades recreativas.',
      'Vigilancia de toma de medicamentos autorizados por sus médicos tratantes.',
      'Toma de signos vitales.',
      'Apoyo en las actividades de la vida diaria.',
      'Traslados desde y hacia su residencia (valor adicional).'
    ],
    url: 'https://res.cloudinary.com/de5tm90td/image/upload/f_auto,q_auto,w_800/v1/assets/wgbojj4lpes6ctsb78kb'
  }
];

export default programs;
